name = "Les Mates"
author = "MmeCromatique"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2174f4aaae9d9b0e6d2b9b2fd43c60a5b421ac61fdefe5ff0bf770a7af11a59e"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
