name = "Les Mates"
author = "MmeCromatique"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4ce1b8b7eb52fb89c541346aa4d7ed987a940d9056d295bb2a1088e52d00b285"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
